//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empleadox.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tb_empleados
    {
        public int id_empleado { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public string correo { get; set; }
        public string cargo { get; set; }
        public string departamento { get; set; }
        public System.DateTime fecha_contratacion { get; set; }
        public decimal salario { get; set; }
        public string rango { get; set; }
        public byte[] curriculum { get; set; }
    }
}
